import "./globals.css";
import NavDemo from "./components/ui/NavDemo";
import Script from "next/script"; 
import WhatsAppButton from "@/app/components/custombtns/WhatsAppButton ";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Model Viewer CDN */}
        <Script
          type="module"
          src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className="antialiased">
        {/* Navbar */}
        <NavDemo />

        {/* Page Content */}
        <main>{children}</main>

        {/* WhatsApp button fixed bottom-right */}
        <div className="fixed bottom-6 right-6 z-50">
          <WhatsAppButton />
        </div>
      </body>
    </html>
  );
}
