import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavDemo from "./components/ui/NavDemo";
import Script from "next/script"; // <-- import Script

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Model Viewer CDN using Next.js Script */}
        <Script
          type="module"
          src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"
          strategy="beforeInteractive" // <-- ensures it loads before app runs
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavDemo />
        <main>{children}</main>
      </body>
    </html>
  );
}
